# Generated by Django 4.0.4 on 2024-10-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strength', models.IntegerField(default=0)),
                ('Weight', models.IntegerField(default=0)),
            ],
        ),
    ]
