# Generated by Django 4.0.4 on 2024-10-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0002_player_model_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_model',
            name='author',
        ),
    ]
