# Generated by Django 4.0.4 on 2024-10-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0003_remove_player_model_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='player_model',
        ),
    ]
