# Generated by Django 4.0.4 on 2024-10-11 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RPG', '0004_delete_player_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strength', models.IntegerField(default=0)),
                ('Weight', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default='janus', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
