# Generated by Django 4.0.4 on 2024-10-11 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RPG', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_model',
            name='author',
        ),
        migrations.AddField(
            model_name='player_model',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
