# Generated by Django 4.2.16 on 2024-10-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0006_remove_player_model_author_player_model_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='goblin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strengthlvl', models.IntegerField(default=8)),
                ('HP', models.IntegerField(verbose_name=7)),
                ('AC', models.IntegerField(default=15)),
            ],
        ),
    ]
