# Generated by Django 4.2.16 on 2024-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0010_alter_goblin_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goblin',
            name='HP',
            field=models.IntegerField(verbose_name=6),
        ),
    ]
