# Generated by Django 4.2.16 on 2024-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0011_alter_goblin_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_model',
            name='AC',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player_model',
            name='HP',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='goblin',
            name='HP',
            field=models.IntegerField(default=7),
        ),
    ]
