# Generated by Django 4.2.16 on 2024-10-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0012_player_model_ac_player_model_hp_alter_goblin_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('armor', 'Armor'), ('weapon', 'Weapon'), ('potion', 'Potion')], max_length=50)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RPG.item')),
            ],
            bases=('RPG.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RPG.item')),
            ],
            bases=('RPG.item',),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(blank=True, to='RPG.item')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RPG.player_model')),
            ],
        ),
        migrations.AddField(
            model_name='player_model',
            name='equipped_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RPG.armor'),
        ),
        migrations.AddField(
            model_name='player_model',
            name='equipped_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RPG.weapon'),
        ),
    ]
