# Generated by Django 4.2.16 on 2024-10-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0013_item_armor_weapon_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_model',
            name='equipped_armor',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'armor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_armor', to='RPG.item'),
        ),
        migrations.AlterField(
            model_name='player_model',
            name='equipped_weapon',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'weapon'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_weapon', to='RPG.item'),
        ),
        migrations.DeleteModel(
            name='Armor',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
