# Generated by Django 4.2.16 on 2024-10-16 10:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0014_remove_weapon_item_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_model',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
