# Generated by Django 4.2.16 on 2024-10-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0016_alter_player_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_model',
            name='coins',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('items', models.ManyToManyField(to='RPG.item')),
            ],
        ),
    ]
