# Generated by Django 4.2.16 on 2024-10-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0018_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goblin',
            old_name='Strengthlvl',
            new_name='Strength',
        ),
        migrations.RemoveField(
            model_name='player_model',
            name='Weight',
        ),
        migrations.AddField(
            model_name='goblin',
            name='Dexterity',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='goblin',
            name='name',
            field=models.CharField(default='goblin', max_length=100),
        ),
        migrations.AddField(
            model_name='player_model',
            name='Dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player_model',
            name='is_in_combat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='player_model',
            name='Strength',
            field=models.IntegerField(default=10),
        ),
    ]
