# Generated by Django 4.2.16 on 2024-10-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0019_rename_strengthlvl_goblin_strength_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attack',
        ),
        migrations.AddField(
            model_name='item',
            name='damage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
